### ISSUE TITLE
Issues About Code

### ISSUE THREAD

**Issue by XM-Dong** [jinhaoduan/SAR#1]
I'm quite interested in this work, may I ask when the code can be released?

**Comment by jinhaoduan** [comment]
Thanks for your interest. The code will be released once our paper gets accepted.

**Comment by trantrikien239** [comment]
Hi Jinhao, any update on the code release? Thanks.

**Comment by jinhaoduan** [comment]
We have updated our codebase. Please feel free to open issues if you encounter other questions.
