### ISSUE TITLE
Question about the baseline: Semantic Uncertainty (SE)

### ISSUE THREAD

**Issue by ZhangzihanGit** [jinhaoduan/SAR#2]
Hi, thanks for your interesting work.
I notice that [Semantic Uncertainty (SE)](https://openreview.net/forum?id=VD-AYtP0dve) is one of your experiment baselines, did you re-implement it yourself or use their provided code? I'm asking because I didn't find the official code of the paper. If you know where the repo is, please kindly share. Thanks!

**Comment by jinhaoduan** [comment]
Thanks for your interest. Please refer to https://github.com/lorenzkuhn/semantic_uncertainty

**Comment by ZhangzihanGit** [comment]
Thank you!
