### ISSUE TITLE
Negative value

### ISSUE THREAD

**Issue by 2222sssss** [jinhaoduan/SAR#3]
Hello, when I use SAR to quantify uncertainty, it seems that the final value easily becomes negative. Is this normal? How should I consider the choice of the temperature parameter t? ^^

**Comment by jinhaoduan** [comment]
Thank you for your interest. Yes, it is normal to be negative. For temperature $t$, I recommend using the default value of 0.001. You can also explore other options from our ablation study (see Table 5 in Appendix C.1), although the differences are not very significant.
